### ISSUE TITLE
Streamlit not launching

### ISSUE THREAD

**Issue by meechos** [cloudera/CML_AMP_Streamlit_on_CML#1]
Application appears to be running but browser is not launching and stuck at `starting`
![image](https://user-images.githubusercontent.com/429321/117990164-cd5c9480-b334-11eb-98ba-970f80ce0a88.png)
![image](https://user-images.githubusercontent.com/429321/117990342-fed56000-b334-11eb-95dc-c6c5e02a9e6d.png)

Env CDSW:
> In a CML workspace, click "New Project", add a Project Name, select "Git" as the Initial Setup option, copy in the repo URL, click "Create Project". Launch a Python 3 Workbench Session and run !pip3 install -r requirements.txt to install requirements. Then create a CML Application as described in the CML documentation, using app.py as the script.

Application script:
```bash
!streamlit run /home/cdsw/app.py --browser.serverPort 8100
```

**Comment by cjwallace** [comment]
Hi @meechos. There's a tested launch script in the `cml` directory - does that work for you?

https://github.com/cloudera/CML_AMP_Streamlit_on_CML/blob/master/cml/launch_app.py

I think I can improve the README here.

**Comment by cjwallace** [comment]
The README was providing incorrect instructions - I've changed it to point to the correct script to use to launch the app. Thanks for raising! Let me know if this works 🙂 

In case you're interested in the technical reason your script didn't work, by default, Streamlit attempts to bind to all network addresses it can see, and in CML the public addresses are taken, so we need to give it a server address.
